def convert_language2(language_from="auto", language_to="English",):
    if language_to != "":
        _language_to = list(_langs.keys())[list(_langs.values()).index(language_to)]
    else:
        _language_to = list(_langs.keys())[list(_langs.values()).index("English")]

    if language_from != "":
        _language_from = list(_langs.keys())[list(_langs.values()).index(language_from)]
    else:
        _language_from = list(_langs.keys())[list(_langs.values()).index("auto")]

    return _language_from, _language_to


def find_key(dictionary, value):
    for key, subdictionary in dictionary.items():
        for subkey, subvalue in subdictionary.items():
            if subvalue == value:
                return subkey
    return None


def convert_language(language_from="auto", language_to="English",):
    if language_to != "":
        _language_to = find_key(services_translators_languages, language_to)
    else:
        _language_to = 'en'

    if language_from != "":
        _language_from = find_key(services_translators_languages, language_from)
    else:
        _language_from = "auto"

    return _language_from, _language_to


_langs2 = {"af": "Afrikaans", "ar": "Arabic", "bg": "Bulgarian", "bn": "Bengali", "bs": "Bosnian", "ca": "Catalan", "cs": "Czech", "da": "Danish", "de": "German", "el": "Greek", "en": "English", "es": "Spanish", "et": "Estonian", "fi": "Finnish", "fr": "French", "gu": "Gujarati", "hi": "Hindi", "hr": "Croatian", "hu": "Hungarian", "id": "Indonesian", "is": "Icelandic", "it": "Italian", "iw": "Hebrew", "ja": "Japanese", "jw": "Javanese", "km": "Khmer", "kn": "Kannada", "ko": "Korean", "la": "Latin", "lv": "Latvian", "ml": "Malayalam", "mr": "Marathi", "ms": "Malay", "my": "Myanmar (Burmese)", "ne": "Nepali", "nl": "Dutch", "no": "Norwegian", "pl": "Polish", "pt": "Portuguese", "ro": "Romanian", "ru": "Russian", "si": "Sinhala", "sk": "Slovak", "sq": "Albanian", "sr": "Serbian", "su": "Sundanese", "sv": "Swedish", "sw": "Swahili", "ta": "Tamil", "te": "Telugu", "th": "Thai", "tl": "Filipino", "tr": "Turkish", "uk": "Ukrainian", "ur": "Urdu", "vi": "Vietnamese", "zh-CN": "Chinese (Simplified)", "zh-TW": "Chinese (Traditional)"}
_langs = {"auto": "auto", "detect": "detect", "aa": "Afar", "ab": "Abkhazian", "ace": "Achinese", "acf-LC": "Saint Lucian Creole French (St. Lucia)", "ach": "Acoli", "acr": "Achi", "acu": "Achuar-Shiwiar", "ada": "Adangme", "adh": "Adhola", "ae": "Avestan", "af": "Afrikaans", "af-ZA": "Afrikaans (South Africa)", "af_ZA": "Afrikaans (South Africa)", "afr": "Afrikaans", "agr": "Aguaruna", "aig-AG": "Antigua and Barbuda Creole English (Antigua & Barbuda)", "ak": "Akan", "aka": "Akan", "ake": "Akawaio", "alb": "Albanian", "am": "Amharic", "am-ET": "Amharic (Ethiopia)", "am_ET": "Amharic (Ethiopia)", "amh": "Amharic", "amk": "Ambai", "amu": "Guerrero Amuzgo", "an": "Aragonese", "ang": "Old English", "any": "Anyin", "ar": "Arabic", "ar-AE": "Arabic (United Arab Emirates)", "ar-EG": "Arabic (Egypt)", "ar-SA": "Arabic (Saudi Arabia)", "ar_EG": "Arabic (Egypt)", "ar_SA": "Arabic (Saudi Arabia)", "ara": "Arabic", "arg": "Aragonese", "arm": "Armenian", "arn": "Mapuche", "arq": "Algerian Arabic", "as": "Assamese", "as_IN": "Assamese (India)", "asm": "Assamese", "ast": "Asturian", "ata": "Pele-Ata", "av": "Avaric", "ay": "Aymara", "aym": "Aymara", "az": "Azerbaijani", "az-AZ": "Azerbaijani (Azerbaijan)", "az_AZ": "Azerbaijani (Azerbaijan)", "azb": "South Azerbaijani", "aze": "Azerbaijani", "ba": "Bashkir", "bah-BS": "Bahamas Creole English (Bahamas)", "bak": "Bashkir", "bal": "Baluchi", "bam": "Bambara", "ban": "Balinese", "baq": "Basque", "bas": "Basaa", "bba": "Baatonum", "bch": "Bariai", "bci": "Baoulé", "bcl": "Central Bikol", "bdh": "Baka (South Sudan)", "bdu": "Oroko", "be": "Belarusian", "be-BY": "Belarusian (Belarus)", "be_BY": "Belarusian (Belarus)", "bel": "Belarusian", "bem": "Bemba", "bem-ZM": "Bemba (Zambia)", "ben": "Bangla", "ber": "Berber languages", "bfa": "Bari", "bg": "Bulgarian", "bg-BG": "Bulgarian (Bulgaria)", "bg_BG": "Bulgarian (Bulgaria)", "bh": "Bihari languages", "bho": "Bhojpuri", "bhw": "Biak", "bi": "Bislama", "bi-VU": "Bislama (Vanuatu)", "bin": "Bini", "bis": "Bislama", "bjn": "Banjar", "bjs-BB": "Bajan (Barbados)", "bli": "Bolia", "bm": "Bambara", "bn": "Bangla", "bn-IN": "Bangla (India)", "bn_BD": "Bangla (Bangladesh)", "bno": "Bantoanon", "bnp": "Bola", "bo": "Tibetan", "bo-CN": "Tibetan (China)", "bos": "Bosnian", "bqj": "Bandial", "bqp": "Busa", "br": "Breton", "br-FR": "Breton (France)", "bre": "Breton", "bs": "Bosnian", "bs-BA": "Bosnian (Bosnia & Herzegovina)", "bs_BA": "Bosnian (Bosnia & Herzegovina)", "bsn": "Barasana-Eduria", "btx": "Batak Karo", "bug": "Buginese", "bul": "Bulgarian", "bum": "Bulu", "bur": "Burmese", "bus": "Bokobaru", "byn": "Blin", "byr": "Baruya", "bzj": "Belize Kriol English", "ca": "Catalan", "ca-ES": "Catalan (Spain)", "ca_ES": "Catalan (Spain)", "cab": "Garifuna", "cak": "Kaqchikel", "cas": "Tsimané", "cat": "Catalan", "cbk": "Chavacano", "cbl": "Bualkhaw Chin", "cce": "Chopi", "ccp": "Chakma", "cdf": "Chiru", "ce": "Chechen", "ceb": "Cebuano", "ceb_PH": "Cebuano (Philippines)", "cfm": "Falam Chin", "cgg": "Chiga", "ch": "Chamorro", "ch-GU": "Chamorro (Guam)", "cha": "Chamorro", "che": "Chechen", "chk": "Chuukese", "chm": "Mari", "chq": "Quiotepec Chinantec", "chr": "Cherokee", "cht": "Cholón", "chv": "Chuvash", "cjk": "Chokwe", "cjp": "Cabécar", "ckb": "Central Kurdish", "ckb-IQ": "Central Kurdish (Iraq)", "cnh": "Hakha Chin", "cni": "Asháninka", "cnr": "Serbian (Montenegro)", "co": "Corsican", "co_FR": "Corsican (France)", "cop": "Coptic", "cop-EG": "Coptic (Egypt)", "cor": "Cornish", "cos": "Corsican", "cpb": "Ucayali-Yurúa Ashéninka", "cr": "Cree", "cre": "Cree", "crh": "Crimean Turkish", "cri": "Sãotomense", "crs": "Seselwa Creole French", "crs-SC": "Seselwa Creole French (Seychelles)", "cs": "Czech", "cs-CZ": "Czech (Czechia)", "cs_CZ": "Czech (Czechia)", "csb": "Kashubian", "ctd": "Tedim Chin", "cu": "Church Slavic", "cv": "Chuvash", "cy": "Welsh", "cy-GB": "Welsh (United Kingdom)", "cy_GB": "Welsh (United Kingdom)", "czt": "Zotung Chin", "da": "Danish", "da-DK": "Danish (Denmark)", "da_DK": "Danish (Denmark)", "dan": "Danish", "de": "German", "de-CH": "German (Switzerland)", "de-DE": "German (Germany)", "de_DE": "German (Germany)", "dev": "Domung", "dhv": "Dehu", "dik": "Southwestern Dinka", "div": "Divehi", "dje": "Zarma", "djk": "Eastern Maroon Creole", "doi": "Dogri", "dop": "Lukpa", "dtp": "Central Dusun", "dua": "Duala", "duo": "Dupaninan Agta", "dv": "Divehi", "dv-MV": "Divehi (Maldives)", "dyu": "Dyula", "dz": "Dzongkha", "dz-BT": "Dzongkha (Bhutan)", "ee": "Ewe", "efi": "Efik", "el": "Greek", "el-GR": "Greek (Greece)", "el_GR": "Greek (Greece)", "en": "English", "en-AU": "English (Australia)", "en-GB": "English (United Kingdom)", "en-UK": "English (United Kingdom)", "en-US": "English (United States)", "en-gb": "English (United Kingdom)", "en_GB": "English (United Kingdom)", "eno": "Enggano", "enx": "Enxet", "eo": "Esperanto", "eo-EU": "Esperanto (European Union)", "eo_WORLD": "Esperanto", "epo": "Esperanto", "es": "Spanish", "es-419": "Spanish (Latin America)", "es-ES": "Spanish (Spain)", "es-MX": "Spanish (Mexico)", "es-US": "Spanish (United States)", "es-la": "Spanish (Laos)", "es_ES": "Spanish (Spain)", "est": "Estonian", "et": "Estonian", "et-EE": "Estonian (Estonia)", "et_EE": "Estonian (Estonia)", "eu": "Basque", "eu-ES": "Basque (Spain)", "eu_ES": "Basque (Spain)", "fa": "Persian", "fa-IR": "Persian (Iran)", "fa_IR": "Persian (Iran)", "fao": "Faroese", "ff": "Fulah", "fi": "Finnish", "fi-FI": "Finnish (Finland)", "fi_FI": "Finnish (Finland)", "fil": "Filipino", "fin": "Finnish", "fj": "Fijian", "fo": "Faroese", "fo-FO": "Faroese (Faroe Islands)", "fr": "French", "fr-CA": "French (Canada)", "fr-FR": "French (France)", "fr-ca": "French (Canada)", "fr_CA": "French (Canada)", "fr_FR": "French (France)", "fra": "French", "frm": "Middle French", "fry": "Western Frisian", "ful": "Fulah", "fur": "Friulian", "fuv": "Nigerian Fulfulde", "fvr": "Fur", "fy": "Western Frisian", "fy_NL": "Western Frisian (Netherlands)", "ga": "Irish", "ga-IE": "Irish (Ireland)", "ga_IE": "Irish (Ireland)", "gaa": "Ga", "gbi": "Galela", "gbo": "Northern Grebo", "gcl-GD": "Grenadian Creole English (Grenada)", "gd": "Scottish Gaelic", "gd-GB": "Scottish Gaelic (United Kingdom)", "gd_GB": "Scottish Gaelic (United Kingdom)", "geo": "Georgian", "gil": "Gilbertese", "gl": "Galician", "gl-ES": "Galician (Spain)", "gl_ES": "Galician (Spain)", "gla": "Scottish Gaelic", "gle": "Irish", "glg": "Galician", "glv": "Manx", "gn": "Guarani", "gnw": "Western Bolivian Guaraní", "gof": "Gofa", "gom": "Goan Konkani", "gos": "Gronings", "gra": "Rajput Garasia", "grc-GR": "Ancient Greek (Greece)", "grn": "Guarani", "gu": "Gujarati", "gu-IN": "Gujarati (India)", "gu_IN": "Gujarati (India)", "gub": "Guajajára", "guc": "Wayuu", "gug": "Paraguayan Guaraní", "guj": "Gujarati", "gun": "Mbyá Guaraní", "gur": "Frafra", "guw": "Gun", "gv": "Manx", "gv-IM": "Manx (Isle of Man)", "gym": "Ngäbere", "gyn-GY": "Guyanese Creole English (Guyana)", "ha": "Hausa", "ha-NE": "Hausa (Niger)", "ha_NE": "Hausa (Niger)", "hak": "Hakka Chinese", "hau": "Hausa", "haw": "Hawaiian", "haw-US": "Hawaiian (United States)", "haw_US": "Hawaiian (United States)", "hbs": "Serbian (Latin)", "he": "Hebrew", "he-IL": "Hebrew (Israel)", "he_IL": "Hebrew (Israel)", "heb": "Hebrew", "her": "Herero", "hi": "Hindi", "hi-IN": "Hindi (India)", "hi-latn": "Hindi (Latin)", "hi_IN": "Hindi (India)", "hil": "Hiligaynon", "hlb": "Halbi", "hmn": "Hmong", "hmn_CN": "Hmong (China)", "hmo": "Hiri Motu", "ho": "Hiri Motu", "hr": "Croatian", "hr-HR": "Croatian (Croatia)", "hr_HR": "Croatian (Croatia)", "hrv": "Croatian", "hsb": "Upper Sorbian", "ht": "Haitian Creole", "ht-HT": "Haitian Creole (Haiti)", "ht_HT": "Haitian Creole (Haiti)", "hu": "Hungarian", "hu-HU": "Hungarian (Hungary)", "hu_HU": "Hungarian (Hungary)", "hui": "Huli", "hup": "Hupa", "huv": "San Mateo Del Mar Huave", "hwc": "Hawai'i Creole English", "hy": "Armenian", "hy-AM": "Armenian (Armenia)", "hy_AM": "Armenian (Armenia)", "hz": "Herero", "ia": "Interlingua", "iba": "Iban", "ibg": "Ibanag", "ibo": "Igbo", "ice": "Icelandic", "id": "Indonesian", "id-ID": "Indonesian (Indonesia)", "id_ID": "Indonesian (Indonesia)", "ido": "Ido", "ie": "Interlingue", "ifa": "Amganad Ifugao", "ifb": "Batad Ifugao", "ify": "Keley-I Kallahan", "ig": "Igbo", "ig_NG": "Igbo (Nigeria)", "ii": "Sichuan Yi", "ik": "Inupiaq", "ikk": "Ika", "ikt": "Inuinnaqtun", "iku": "Inuktitut", "ilo": "Iloko", "ina": "Interlingua", "ing": "Degexit'an", "inh": "Ingush", "io": "Ido", "iou": "Tuma-Irumu", "is": "Icelandic", "is-IS": "Icelandic (Iceland)", "is_IS": "Icelandic (Iceland)", "ish": "Esan", "iso": "Isoko", "it": "Italian", "it-IT": "Italian (Italy)", "it_IT": "Italian (Italy)", "iu": "Inuktitut", "iu-Latn": "Inuktitut (Latin)", "iw": "Hebrew", "izz": "Izii", "ja": "Japanese", "ja-JP": "Japanese (Japan)", "ja_JP": "Japanese (Japan)", "jac": "Popti'", "jae": "Yabem", "jam-JM": "Jamaican Creole English (Jamaica)", "jav": "Javanese", "jbo": "Lojban", "jiv": "Shuar", "jmc": "Machame", "jv": "Javanese", "jv-ID": "Javanese (Indonesia)", "jv_ID": "Javanese (Indonesia)", "jw": "Javanese", "ka": "Georgian", "ka-GE": "Georgian (Georgia)", "ka_GE": "Georgian (Georgia)", "kab": "Kabyle", "kab-DZ": "Kabyle (Algeria)", "kac": "Kachin", "kah": "Kara (Central African Republic)", "kal": "Kalaallisut", "kam": "Kamba", "kan": "Kannada", "kas": "Kashmiri", "kau": "Kanuri", "kbh": "Camsá", "kbo": "Keliko", "kbp": "Kabiyè", "kdx": "Kam", "kea": "Kabuverdianu", "kea-CV": "Kabuverdianu (Cape Verde)", "kek": "Kekchí", "keo": "Kakwa", "kg": "Kongo", "kha": "Khasi", "ki": "Kikuyu", "kik": "Kikuyu", "kin": "Kinyarwanda", "kir": "Kyrgyz", "kj": "Kuanyama", "kk": "Kazakh", "kk-KZ": "Kazakh (Kazakhstan)", "kk_KZ": "Kazakh (Kazakhstan)", "kl": "Kalaallisut", "kl-GL": "Kalaallisut (Greenland)", "kle": "Kulung (Nepal)", "kli": "Kalumpang", "km": "Khmer", "km-KM": "Khmer (Comoros)", "km_KH": "Khmer (Cambodia)", "kmb": "Kimbundu", "kmr": "Northern Kurdish", "kn": "Kannada", "kn-IN": "Kannada (India)", "kn_IN": "Kannada (India)", "knj": "Western Kanjobal", "ko": "Korean", "ko-KR": "Korean (South Korea)", "ko_KR": "Korean (South Korea)", "kok": "Konkani", "kon": "Kongo", "kor": "Korean", "kpg": "Kapingamarangi", "kqn": "Kaonde", "kr": "Kanuri", "kri": "Krio", "krs": "Gbaya (Sudan)", "ks": "Kashmiri", "ksd": "Kuanua", "ku": "Kurdish", "ku-TR": "Kurdish (Turkey)", "ku_IR": "Kurdish (Iran)", "kur": "Kurdish", "kv": "Komi", "kw": "Cornish", "kwy": "San Salvador Kongo", "ky": "Kyrgyz", "ky-KG": "Kyrgyz (Kyrgyzstan)", "ky_KG": "Kyrgyz (Kyrgyzstan)", "kyu": "Western Kayah", "la": "Latin", "la-VA": "Latin (Vatican City)", "la_VAT": "Latin", "lag": "Langi", "lao": "Lao", "lat": "Latin", "lav": "Latvian", "lb": "Luxembourgish", "lb-LU": "Luxembourgish (Luxembourg)", "lb_LU": "Luxembourgish (Luxembourg)", "lcm": "Tungag", "lcp": "Western Lawa", "lg": "Ganda", "li": "Limburgish", "lim": "Limburgish", "lin": "Lingala", "lit": "Lithuanian", "ln": "Lingala", "lnd": "Lundayeh", "lo": "Lao", "lo-LA": "Lao (Laos)", "lo_LA": "Lao (Laos)", "log": "Logo", "loj": "Lou", "los": "Loniu", "loz": "Lozi", "lsi": "Lashi", "lt": "Lithuanian", "lt-LT": "Lithuanian (Lithuania)", "lt_LT": "Lithuanian (Lithuania)", "ltg": "Latgalian", "ltz": "Luxembourgish", "lu": "Luba-Katanga", "lua": "Luba-Lulua", "lub": "Luba-Katanga", "lue": "Luvale", "lug": "Ganda", "lun": "Lunda", "lus": "Mizo", "lv": "Latvian", "lv-LV": "Latvian (Latvia)", "lv_LV": "Latvian (Latvia)", "lzh": "Literary Chinese", "mac": "Macedonian", "mad": "Madurese", "mag": "Magahi", "mah": "Marshallese", "mai": "Maithili", "mal": "Malayalam", "mam": "Mam", "mao": "Māori", "map": "Austronesian languages", "mar": "Marathi", "mau": "Huautla Mazatec", "may": "Malay", "mbb": "Western Bukidnon Manobo", "mdy": "Male (Ethiopia)", "men-SL": "Mende (Sierra Leone)", "meu": "Motu", "mfe": "Morisyen", "mfe-MU": "Morisyen (Mauritius)", "mg": "Malagasy", "mg-MG": "Malagasy (Madagascar)", "mg_MG": "Malagasy (Madagascar)", "mh": "Marshallese", "mh-MH": "Marshallese (Marshall Islands)", "mhr": "Eastern Mari", "mi": "Māori", "mi-NZ": "Māori (New Zealand)", "mi_NZ": "Māori (New Zealand)", "min": "Minangkabau", "mk": "Macedonian", "mk-MK": "Macedonian (North Macedonia)", "mk_MK": "Macedonian (North Macedonia)", "ml": "Malayalam", "ml_IN": "Malayalam (India)", "mlt": "Maltese", "mn": "Mongolian", "mn-Cyrl": "Mongolian (Cyrillic)", "mn-MN": "Mongolian (Mongolia)", "mn-Mong": "Mongolian (Mongolian)", "mn_MN": "Mongolian (Mongolia)", "mni": "Manipuri", "mni-Mtei": "Manipuri (Meitei Mayek)", "mnk": "Mandinka", "mo": "Romanian", "mon": "Mongolian", "mos": "Mossi", "mot": "Barí", "mps": "Dadibi", "mr": "Marathi", "mr_IN": "Marathi (India)", "mrj": "Western Mari", "mrw": "Maranao", "ms": "Malay", "ms-MY": "Malay (Malaysia)", "ms_MY": "Malay (Malaysia)", "mt": "Maltese", "mt-MT": "Maltese (Malta)", "mt_MT": "Maltese (Malta)", "mus": "Muscogee", "muv": "Muthuvan", "mww": "Hmong Daw", "my": "Burmese", "my-MM": "Burmese (Myanmar (Burma))", "my_MM": "Burmese (Myanmar (Burma))", "na": "Nauru", "nah": "Nahuatl languages", "nap": "Neapolitan", "nav": "Navajo", "nb": "Norwegian Bokmål", "nba": "Nyemba", "nbl": "South Ndebele", "nch": "Central Huasteca Nahuatl", "nd": "North Ndebele", "ndc": "Ndau", "ndo": "Ndonga", "nds": "Low German", "ne": "Nepali", "ne-NP": "Nepali (Nepal)", "ne_NP": "Nepali (Nepal)", "nea": "Eastern Ngad'a", "nep": "Nepali", "ng": "Ndonga", "ngl": "Lomwe", "ngu": "Guerrero Nahuatl", "nhg": "Tetelcingo Nahuatl", "nia": "Nias", "nij": "Ngaju", "niu": "Niuean", "niu-NU": "Niuean (Niue)", "nl": "Dutch", "nl-NL": "Dutch (Netherlands)", "nl_NL": "Dutch (Netherlands)", "nn": "Norwegian Nynorsk", "nno": "Norwegian Nynorsk", "no": "Norwegian", "no-NO": "Norwegian (Norway)", "no_NO": "Norwegian (Norway)", "nob": "Norwegian Bokmål", "nop": "Numanggang", "nor": "Norwegian", "nqo": "N’Ko", "nr": "South Ndebele", "nso": "Northern Sotho", "ntm": "Nateni", "nv": "Navajo", "ny": "Nyanja", "ny-MW": "Nyanja (Malawi)", "ny_MW": "Nyanja (Malawi)", "nya": "Nyanja", "nyk": "Nyaneka", "nyn": "Nyankole", "nyu": "Nyungwe", "nyy": "Nyakyusa-Ngonde", "nzi": "Nzima", "oc": "Occitan", "oci": "Occitan", "oj": "Ojibwa", "ojb": "Northwestern Ojibwa", "oji": "Ojibwa", "om": "Oromo", "or": "Odia", "or_OR": "Odia (Unknown Region [OR])", "ori": "Odia", "orm": "Oromo", "os": "Ossetic", "oss": "Ossetic", "otq": "Querétaro Otomi", "pa": "Punjabi", "pa-IN": "Punjabi (India)", "pa_PK": "Punjabi (Pakistan)", "pag": "Pangasinan", "pam": "Pampanga", "pan": "Punjabi", "pap": "Papiamento", "pap-CW": "Papiamento (Curaçao)", "pau-PW": "Palauan (Palau)", "pck": "Paite Chin", "pcm": "Nigerian Pidgin", "ped": "Mala (Papua New Guinea)", "per": "Persian", "pi": "Pali", "pil": "Yom", "pis": "Pijin", "pis-SB": "Pijin (Solomon Islands)", "pl": "Polish", "pl-PL": "Polish (Poland)", "pl_PL": "Polish (Poland)", "plt": "Plateau Malagasy", "pmn": "Pam", "pms": "Piedmontese", "poh": "Poqomchi'", "pon": "Pohnpeian", "pot": "Potawatomi", "pot-US": "Potawatomi (United States)", "pov-GW": "Upper Guinea Crioulo (Guinea-Bissau)", "ppk": "Uma", "ppk-ID": "Uma (Indonesia)", "prk": "Parauk", "prs": "Persian (Afghanistan)", "ps": "Pashto", "ps-PK": "Pashto (Pakistan)", "ps_AF": "Pashto (Afghanistan)", "pss": "Kaulong", "pt": "Portuguese", "pt-BR": "Portuguese (Brazil)", "pt-PT": "Portuguese (Portugal)", "pt-br": "Portuguese (Brazil)", "pt_PT": "Portuguese (Portugal)", "ptu": "Bambam", "pus": "Pashto", "qu": "Quechua", "qu-PE": "Quechua (Peru)", "quc": "Kʼicheʼ", "que": "Quechua", "quh": "South Bolivian Quechua", "quw": "Tena Lowland Quichua", "quz": "Cusco Quechua", "qxr": "Cañar Highland Quichua", "rar": "Rarotongan", "rm": "Romansh", "rm-RO": "Romansh (Romania)", "rmn": "Balkan Romani", "rn": "Rundi", "rn-BI": "Rundi (Burundi)", "rnd": "Ruund", "ro": "Romanian", "ro-RO": "Romanian (Romania)", "ro_RO": "Romanian (Romania)", "roh": "Romansh", "rom": "Romany", "ru": "Russian", "ru-RU": "Russian (Russia)", "ru_RU": "Russian (Russia)", "rue": "Rusyn", "rug": "Roviana", "run": "Rundi", "ruy": "Mala (Nigeria)", "rw": "Kinyarwanda", "rw-RW": "Kinyarwanda (Rwanda)", "rw_RW": "Kinyarwanda (Rwanda)", "sa": "Sanskrit", "sah": "Sakha", "san": "Sanskrit", "sc": "Sardinian", "sco": "Scots", "sd": "Sindhi", "sd_PK": "Sindhi (Pakistan)", "se": "Northern Sami", "sec": "Sechelt", "seh": "Sena", "sg": "Sango", "sg-CF": "Sango (Central African Republic)", "sh": "Serbian (Latin)", "sha": "Shall-Zwall", "shi": "Tachelhit", "shn": "Shan", "shp": "Shipibo-Conibo", "si": "Sinhala", "si-LK": "Sinhala (Sri Lanka)", "si_LK": "Sinhala (Sri Lanka)", "sid": "Sidamo", "sil": "Tumulung Sisaala", "sin": "Sinhala", "sk": "Slovak", "sk-SK": "Slovak (Slovakia)", "sk_SK": "Slovak (Slovakia)", "sl": "Slovenian", "sl-SI": "Slovenian (Slovenia)", "sl_SI": "Slovenian (Slovenia)", "slo": "Slovak", "sm": "Samoan", "sm-WS": "Samoan (Samoa)", "sm_WS": "Samoan (Samoa)", "sme": "Northern Sami", "sn": "Shona", "sn-ZW": "Shona (Zimbabwe)", "sn_ZW": "Shona (Zimbabwe)", "sna": "Shona", "snd": "Sindhi", "so": "Somali", "so-SO": "Somali (Somalia)", "so_SO": "Somali (Somalia)", "sol": "Solos", "som": "Somali", "son": "Songhai languages", "sop": "Songe", "sot": "Southern Sotho", "spa": "Spanish", "spy": "Sabaot", "sq": "Albanian", "sq-AL": "Albanian (Albania)", "sq_AL": "Albanian (Albania)", "sr": "Serbian", "sr-Cyrl": "Serbian (Cyrillic)", "sr-Cyrl_RS": "Serbian (Cyrillic, Serbia)", "sr-Latn": "Serbian (Latin)", "sr-RS": "Serbian (Serbia)", "src": "Logudorese Sardinian", "srd": "Sardinian", "srm": "Saramaccan", "srn-SR": "Sranan Tongo (Suriname)", "srp": "Serbian", "ss": "Swati", "ssd": "Siroi", "ssx": "Samberigi", "st": "Southern Sotho", "st-ST": "Southern Sotho (São Tomé & Príncipe)", "st_LS": "Southern Sotho (Lesotho)", "su": "Sundanese", "su_ID": "Sundanese (Indonesia)", "sun": "Sundanese", "sv": "Swedish", "sv-SE": "Swedish (Sweden)", "sv_SE": "Swedish (Sweden)", "svc-VC": "Vincentian Creole English (St. Vincent & Grenadines)", "sw": "Swahili", "sw-SZ": "Swahili (Eswatini)", "sw_TZ": "Swahili (Tanzania)", "swa": "Swahili", "swc": "Swahili (Congo - Kinshasa)", "swe": "Swedish", "swp": "Suau", "sxn": "Sangir", "syc": "Classical Syriac", "syc-TR": "Classical Syriac (Turkey)", "syr": "Syriac", "szl": "Silesian", "ta": "Tamil", "ta-LK": "Tamil (Sri Lanka)", "ta_IN": "Tamil (India)", "tam": "Tamil", "tat": "Tatar", "tbz": "Ditammari", "tdt": "Tetun Dili", "te": "Telugu", "te-IN": "Telugu (India)", "te_IN": "Telugu (India)", "tel": "Telugu", "teo": "Teso", "tet": "Tetum", "tet-TL": "Tetum (Timor-Leste)", "tex": "Tennet", "tg": "Tajik", "tg-TJ": "Tajik (Tajikistan)", "tg_TJ": "Tajik (Tajikistan)", "tgk": "Tajik", "tgl": "Filipino", "th": "Thai", "th-TH": "Thai (Thailand)", "th_TH": "Thai (Thailand)", "ti": "Tigrinya", "ti-TI": "Tigrinya (Unknown Region [TI])", "tig": "Tigre", "tih": "Timugon Murut", "tir": "Tigrinya", "tiv": "Tiv", "tk": "Turkmen", "tk-TM": "Turkmen (Turkmenistan)", "tk_TM": "Turkmen (Turkmenistan)", "tkl-TK": "Tokelau (Tokelau)", "tl": "Filipino", "tl-PH": "Filipino (Philippines)", "tl_PH": "Filipino (Philippines)", "tlh": "Klingon", "tlh-Latn": "Klingon (Latin)", "tll": "Tetela", "tmh": "Tamashek", "tmh-DZ": "Tamashek (Algeria)", "tn": "Tswana", "tn-BW": "Tswana (Botswana)", "to": "Tongan", "to-TO": "Tongan (Tonga)", "toi": "Tonga (Zambia)", "toj": "Tojolabal", "tpi": "Tok Pisin", "tpi-PG": "Tok Pisin (Papua New Guinea)", "tpm": "Tampulma", "tr": "Turkish", "tr-TR": "Turkish (Turkey)", "tr_TR": "Turkish (Turkey)", "ts": "Tsonga", "tsc": "Tswa", "tso": "Tsonga", "tt": "Tatar", "tt_TT": "Tatar (Trinidad & Tobago)", "ttj": "Tooro", "tua": "Wiarumus", "tuk": "Turkmen", "tum": "Tumbuka", "tvl": "Tuvalu", "tvl-TV": "Tuvalu (Tuvalu)", "tw": "Twi", "twi": "Twi", "ty": "Tahitian", "tyv": "Tuvinian", "tzh": "Tzeltal", "tzo": "Tzotzil", "udm": "Udmurt", "ug": "Uyghur", "ug_CN": "Uyghur (China)", "uk": "Ukrainian", "uk-UA": "Ukrainian (Ukraine)", "uk_UA": "Ukrainian (Ukraine)", "ukr": "Ukrainian", "umb": "Umbundu", "ur": "Urdu", "ur-PK": "Urdu (Pakistan)", "ur_PK": "Urdu (Pakistan)", "urd": "Urdu", "urh": "Urhobo", "usp": "Uspanteco", "uz": "Uzbek", "uz-UZ": "Uzbek (Uzbekistan)", "uz_UZ": "Uzbek (Uzbekistan)", "ve": "Venda", "ven": "Venda", "vi": "Vietnamese", "vi-VN": "Vietnamese (Vietnam)", "vi_VN": "Vietnamese (Vietnam)", "vic-US": "Virgin Islands Creole English (United States)", "vie": "Vietnamese", "vo": "Volapük", "vun": "Vunjo", "wa": "Walloon", "wal": "Wolaytta", "war": "Waray", "wel": "Welsh", "wes": "Cameroon Pidgin", "wln": "Walloon", "wls": "Wallisian", "wls-WF": "Wallisian (Wallis & Futuna)", "wlx": "Wali (Ghana)", "wo": "Wolof", "wo-SN": "Wolof (Senegal)", "wol": "Wolof", "wrs": "Waris", "wsk": "Waskia", "xal": "Kalmyk", "xh": "Xhosa", "xh-ZA": "Xhosa (South Africa)", "xh_ZA": "Xhosa (South Africa)", "xho": "Xhosa", "xle": "Lemnian", "xsm": "Kasem", "yap": "Yapese", "yi": "Yiddish", "yi-YD": "Yiddish (Yemen)", "yi_IL": "Yiddish (Israel)", "yid": "Yiddish", "yo": "Yoruba", "yo_NG": "Yoruba (Nigeria)", "yon": "Yongkom", "yor": "Yoruba", "yua": "Yucateco", "yue": "Cantonese", "za": "Zhuang", "zaz": "Zari", "zdj-KM": "Ngazidja Comorian (Comoros)", "zh": "Chinese", "zh-CHS": "Chinese", "zh-CN": "Chinese (China)", "zh-HK": "Chinese (Hong Kong SAR China)", "zh-Hans": "Chinese (Simplified)", "zh-Hans_CN": "Chinese (Simplified, China)", "zh-Hant": "Chinese (Traditional)", "zh-Hant_TW": "Chinese (Traditional, Taiwan)", "zh-TW": "Chinese (Taiwan)", "zh-tw": "Chinese (Taiwan)", "zne": "Zande (individual language)", "zu": "Zulu", "zu-ZA": "Zulu (South Africa)", "zu_ZA": "Zulu (South Africa)", "zul": "Zulu", "zyb": "Yongbei Zhuang", "zza": "Zaza"}

services_translators_languages = {
    "DeepL": {
        "auto": "auto",
        "ro": "Romanian",
        "bg": "Bulgarian",
        "ko": "Korean",
        "pl": "Polish",
        "cs": "Czech",
        "es": "Spanish",
        "tr": "Turkish",
        "sl": "Slovenian",
        "zh": "Chinese",
        "ja": "Japanese",
        "et": "Estonian",
        "pt": "Portuguese",
        "de": "German",
        "lt": "Lithuanian",
        "el": "Greek",
        "en": "English",
        "fr": "French",
        "nl": "Dutch",
        "lv": "Latvian",
        "it": "Italian",
        "sv": "Swedish",
        "sk": "Slovak",
        "uk": "Ukrainian",
        "fi": "Finnish",
        "hu": "Hungarian",
        "nb": "Norwegian Bokmål",
        "ru": "Russian",
        "id": "Indonesian",
        "da": "Danish",
    },
    "GoogleFree": {
        "auto": "auto",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "Amharic",
        "ar": "Arabic",
        "as": "Assamese",
        "auto": "auto",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bho": "Bhojpuri",
        "bm": "Bambara",
        "bn": "Bangla",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "ckb": "Central Kurdish",
        "co": "Corsican",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "doi": "Dogri",
        "dv": "Divehi",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "en-US": "English (United States)",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gn": "Guarani",
        "gom": "Goan Konkani",
        "gu": "Gujarati",
        "ha": "Hausa",
        "haw": "Hawaiian",
        "hi": "Hindi",
        "hmn": "Hmong",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "ilo": "Iloko",
        "is": "Icelandic",
        "it": "Italian",
        "iw": "Hebrew",
        "ja": "Japanese",
        "jw": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "kri": "Krio",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lus": "Mizo",
        "lv": "Latvian",
        "mai": "Maithili",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mni-Mtei": "Manipuri (Meitei Mayek)",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "nso": "Northern Sotho",
        "ny": "Nyanja",
        "om": "Oromo",
        "or": "Odia",
        "pa": "Punjabi",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "sa": "Sanskrit",
        "sd": "Sindhi",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tl": "Filipino",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "zh-CN": "Chinese (China)",
        "zh-TW": "Chinese (Taiwan)",
        "zu": "Zulu",
    },
    "alibaba": {
        "auto": "auto",
        "ab": "Abkhazian",
        "ace": "Achinese",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "Amharic",
        "an": "Aragonese",
        "ang": "Old English",
        "ar": "Arabic",
        "as": "Assamese",
        "ast": "Asturian",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "bal": "Baluchi",
        "be": "Belarusian",
        "bem": "Bemba",
        "ber": "Berber languages",
        "bg": "Bulgarian",
        "bho": "Bhojpuri",
        "bi": "Bislama",
        "bm": "Bambara",
        "bn": "Bangla",
        "bo": "Tibetan",
        "br": "Breton",
        "bs": "Bosnian",
        "byn": "Blin",
        "ca": "Catalan",
        "cbk": "Chavacano",
        "ceb": "Cebuano",
        "ch": "Chamorro",
        "chm": "Mari",
        "chr": "Cherokee",
        "cnr": "Serbian (Montenegro)",
        "co": "Corsican",
        "crh": "Crimean Turkish",
        "cs": "Czech",
        "csb": "Kashubian",
        "cv": "Chuvash",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dtp": "Central Dusun",
        "dv": "Divehi",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fil": "Filipino",
        "fj": "Fijian",
        "fo": "Faroese",
        "fr": "French",
        "fur": "Friulian",
        "fvr": "Fur",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gil": "Gilbertese",
        "gl": "Galician",
        "gn": "Guarani",
        "gos": "Gronings",
        "gu": "Gujarati",
        "gv": "Manx",
        "ha": "Hausa",
        "haw": "Hawaiian",
        "hbs": "Serbian (Latin)",
        "he": "Hebrew",
        "hi": "Hindi",
        "hil": "Hiligaynon",
        "hmn": "Hmong",
        "hsb": "Upper Sorbian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hup": "Hupa",
        "hy": "Armenian",
        "ia": "Interlingua",
        "iba": "Iban",
        "id": "Indonesian",
        "ie": "Interlingue",
        "ig": "Igbo",
        "ii": "Sichuan Yi",
        "ilo": "Iloko",
        "inh": "Ingush",
        "io": "Ido",
        "is": "Icelandic",
        "it": "Italian",
        "iu": "Inuktitut",
        "ja": "Japanese",
        "jbo": "Lojban",
        "jv": "Javanese",
        "ka": "Georgian",
        "kab": "Kabyle",
        "kdx": "Kam",
        "kek": "Kekchí",
        "kg": "Kongo",
        "kha": "Khasi",
        "kk": "Kazakh",
        "kl": "Kalaallisut",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "kr": "Kanuri",
        "ks": "Kashmiri",
        "ku": "Kurdish",
        "kw": "Cornish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "li": "Limburgish",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "ltg": "Latgalian",
        "lv": "Latvian",
        "mai": "Maithili",
        "mfe": "Morisyen",
        "mg": "Malagasy",
        "mh": "Marshallese",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "mus": "Muscogee",
        "my": "Burmese",
        "nch": "Central Huasteca Nahuatl",
        "nds": "Low German",
        "ne": "Nepali",
        "ngu": "Guerrero Nahuatl",
        "niu": "Niuean",
        "nl": "Dutch",
        "no": "Norwegian",
        "nv": "Navajo",
        "ny": "Nyanja",
        "oc": "Occitan",
        "oj": "Ojibwa",
        "om": "Oromo",
        "or": "Odia",
        "os": "Ossetic",
        "pa": "Punjabi",
        "pag": "Pangasinan",
        "pap": "Papiamento",
        "pl": "Polish",
        "pmn": "Pam",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "quc": "Kʼicheʼ",
        "rm": "Romansh",
        "rn": "Rundi",
        "ro": "Romanian",
        "rom": "Romany",
        "ru": "Russian",
        "rue": "Rusyn",
        "rw": "Kinyarwanda",
        "sa": "Sanskrit",
        "sco": "Scots",
        "sd": "Sindhi",
        "se": "Northern Sami",
        "sg": "Sango",
        "shn": "Shan",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "syr": "Syriac",
        "szl": "Silesian",
        "ta": "Tamil",
        "te": "Telugu",
        "tet": "Tetum",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tl": "Filipino",
        "tlh": "Klingon",
        "toi": "Tonga (Zambia)",
        "tpi": "Tok Pisin",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tvl": "Tuvalu",
        "tw": "Twi",
        "ty": "Tahitian",
        "tyv": "Tuvinian",
        "udm": "Udmurt",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "umb": "Umbundu",
        "ur": "Urdu",
        "uz": "Uzbek",
        "ve": "Venda",
        "vi": "Vietnamese",
        "vo": "Volapük",
        "wa": "Walloon",
        "war": "Waray",
        "wo": "Wolof",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "yue": "Cantonese",
        "za": "Zhuang",
        "zh": "Chinese",
        "zh-tw": "Chinese (Taiwan)",
        "zu": "Zulu",
        "zza": "Zaza",
    },
    "apertium": {
        "auto": "auto",
        "afr": "Afrikaans",
        "ara": "Arabic",
        "arg": "Aragonese",
        "bel": "Belarusian",
        "bre": "Breton",
        "bul": "Bulgarian",
        "cat": "Catalan",
        "crh": "Crimean Turkish",
        "cym": "Welsh",
        "dan": "Danish",
        "eng": "English",
        "epo": "Esperanto",
        "spa": "Spanish",
        "eus": "Basque",
        "fra": "French",
        "frp": "Arpitan",
        "glg": "Galician",
        "hbs": "Serbian (Latin)",
        "hin": "Hindi",
        "ind": "Indonesian",
        "isl": "Icelandic",
        "ita": "Italian",
        "kaz": "Kazakh",
        "mkd": "Macedonian",
        "mlt": "Maltese",
        "nld": "Dutch",
        "nno": "Norwegian Nynorsk",
        "nno_e": "nno_e",
        "nob": "Norwegian Bokmål",
        "oci": "Occitan",
        "oci_aran": "Occitan (Nastaliq)",
        "oci_gascon": "Occitan",
        "pol": "Polish",
        "por": "Portuguese",
        "ron": "Romanian",
        "rus": "Russian",
        "slv": "Slovenian",
        "sme": "Northern Sami",
        "swe": "Swedish",
        "szl": "Silesian",
        "tat": "Tatar",
        "tur": "Turkish",
        "ukr": "Ukrainian",
        "urd": "Urdu",
        "zlm": "Malay (individual language)",
    },
    "argos": {
        "auto": "auto",
        "ar": "Arabic",
        "de": "German",
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "ga": "Irish",
        "hi": "Hindi",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "ko": "Korean",
        "pl": "Polish",
        "pt": "Portuguese",
        "ru": "Russian",
        "tr": "Turkish",
        "vi": "Vietnamese",
        "zh": "Chinese",
    },
    "baidu": {
        "auto": "auto",
        "ach": "Acoli",
        "afr": "Afrikaans",
        "aka": "Akan",
        "alb": "Albanian",
        "amh": "Amharic",
        "ara": "Arabic",
        "arg": "Aragonese",
        "arm": "Armenian",
        "arq": "Algerian Arabic",
        "asm": "Assamese",
        "ast": "Asturian",
        "aym": "Aymara",
        "aze": "Azerbaijani",
        "bak": "Bashkir",
        "bal": "Baluchi",
        "baq": "Basque",
        "bel": "Belarusian",
        "bem": "Bemba",
        "ben": "Bangla",
        "ber": "Berber languages",
        "bho": "Bhojpuri",
        "bis": "Bislama",
        "bli": "Bolia",
        "bos": "Bosnian",
        "bre": "Breton",
        "bul": "Bulgarian",
        "bur": "Burmese",
        "cat": "Catalan",
        "ceb": "Cebuano",
        "chr": "Cherokee",
        "cht": "Cholón",
        "chv": "Chuvash",
        "cor": "Cornish",
        "cos": "Corsican",
        "cre": "Cree",
        "cri": "Sãotomense",
        "cs": "Czech",
        "dan": "Danish",
        "de": "German",
        "div": "Divehi",
        "el": "Greek",
        "en": "English",
        "eno": "Enggano",
        "epo": "Esperanto",
        "est": "Estonian",
        "fao": "Faroese",
        "fil": "Filipino",
        "fin": "Finnish",
        "fra": "French",
        "fri": "fri",
        "frm": "Middle French",
        "frn": "frn",
        "fry": "Western Frisian",
        "ful": "Fulah",
        "geo": "Georgian",
        "gla": "Scottish Gaelic",
        "gle": "Irish",
        "glg": "Galician",
        "glv": "Manx",
        "gra": "Rajput Garasia",
        "grn": "Guarani",
        "guj": "Gujarati",
        "hak": "Hakka Chinese",
        "hau": "Hausa",
        "haw": "Hawaiian",
        "heb": "Hebrew",
        "hi": "Hindi",
        "hil": "Hiligaynon",
        "hkm": "hkm",
        "hmn": "Hmong",
        "hrv": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hup": "Hupa",
        "ibo": "Igbo",
        "ice": "Icelandic",
        "id": "Indonesian",
        "ido": "Ido",
        "iku": "Inuktitut",
        "ina": "Interlingua",
        "ing": "Degexit'an",
        "it": "Italian",
        "jav": "Javanese",
        "jp": "jp",
        "kab": "Kabyle",
        "kah": "Kara (Central African Republic)",
        "kal": "Kalaallisut",
        "kan": "Kannada",
        "kas": "Kashmiri",
        "kau": "Kanuri",
        "kin": "Kinyarwanda",
        "kir": "Kyrgyz",
        "kli": "Kalumpang",
        "kok": "Konkani",
        "kon": "Kongo",
        "kor": "Korean",
        "kur": "Kurdish",
        "lag": "Langi",
        "lao": "Lao",
        "lat": "Latin",
        "lav": "Latvian",
        "lim": "Limburgish",
        "lin": "Lingala",
        "lit": "Lithuanian",
        "log": "Logo",
        "loj": "Lou",
        "los": "Loniu",
        "ltz": "Luxembourgish",
        "lug": "Ganda",
        "mac": "Macedonian",
        "mah": "Marshallese",
        "mai": "Maithili",
        "mal": "Malayalam",
        "mao": "Māori",
        "mar": "Marathi",
        "mau": "Huautla Mazatec",
        "may": "Malay",
        "mg": "Malagasy",
        "mlt": "Maltese",
        "mot": "Barí",
        "nbl": "South Ndebele",
        "nea": "Eastern Ngad'a",
        "nep": "Nepali",
        "nl": "Dutch",
        "nno": "Norwegian Nynorsk",
        "nob": "Norwegian Bokmål",
        "nor": "Norwegian",
        "nqo": "N’Ko",
        "nya": "Nyanja",
        "oci": "Occitan",
        "oji": "Ojibwa",
        "ori": "Odia",
        "orm": "Oromo",
        "oss": "Ossetic",
        "pam": "Pampanga",
        "pan": "Punjabi",
        "pap": "Papiamento",
        "ped": "Mala (Papua New Guinea)",
        "per": "Persian",
        "pl": "Polish",
        "pot": "Potawatomi",
        "pt": "Portuguese",
        "pus": "Pashto",
        "que": "Quechua",
        "ro": "Romanian",
        "roh": "Romansh",
        "rom": "Romany",
        "ru": "Russian",
        "ruy": "Mala (Nigeria)",
        "san": "Sanskrit",
        "sco": "Scots",
        "sec": "Sechelt",
        "sha": "Shall-Zwall",
        "sil": "Tumulung Sisaala",
        "sin": "Sinhala",
        "sk": "Slovak",
        "slo": "Slovak",
        "sm": "Samoan",
        "sme": "Northern Sami",
        "sna": "Shona",
        "snd": "Sindhi",
        "sol": "Solos",
        "som": "Somali",
        "sot": "Southern Sotho",
        "spa": "Spanish",
        "src": "Logudorese Sardinian",
        "srd": "Sardinian",
        "srp": "Serbian",
        "sun": "Sundanese",
        "swa": "Swahili",
        "swe": "Swedish",
        "syr": "Syriac",
        "tam": "Tamil",
        "tat": "Tatar",
        "tel": "Telugu",
        "tet": "Tetum",
        "tgk": "Tajik",
        "tgl": "Filipino",
        "th": "Thai",
        "tir": "Tigrinya",
        "tr": "Turkish",
        "tso": "Tsonga",
        "tua": "Wiarumus",
        "tuk": "Turkmen",
        "twi": "Twi",
        "ukr": "Ukrainian",
        "ups": "ups",
        "urd": "Urdu",
        "ven": "Venda",
        "vie": "Vietnamese",
        "wel": "Welsh",
        "wln": "Walloon",
        "wol": "Wolof",
        "wyw": "wyw",
        "xho": "Xhosa",
        "yid": "Yiddish",
        "yor": "Yoruba",
        "yue": "Cantonese",
        "zaz": "Zari",
        "zh": "Chinese",
        "zul": "Zulu",
    },
    "bing": {
        "auto": "auto",
        "af": "Afrikaans",
        "am": "Amharic",
        "ar": "Arabic",
        "as": "Assamese",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "bo": "Tibetan",
        "bs": "Bosnian",
        "ca": "Catalan",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dv": "Divehi",
        "el": "Greek",
        "en": "English",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fil": "Filipino",
        "fj": "Fijian",
        "fo": "Faroese",
        "fr": "French",
        "fr-CA": "French (Canada)",
        "ga": "Irish",
        "gl": "Galician",
        "gu": "Gujarati",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "ikt": "Inuinnaqtun",
        "is": "Icelandic",
        "it": "Italian",
        "iu": "Inuktitut",
        "iu-Latn": "Inuktitut (Latin)",
        "ja": "Japanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kmr": "Northern Kurdish",
        "kn": "Kannada",
        "ko": "Korean",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lug": "Ganda",
        "lv": "Latvian",
        "lzh": "Literary Chinese",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn-Cyrl": "Mongolian (Cyrillic)",
        "mn-Mong": "Mongolian (Mongolian)",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "mww": "Hmong Daw",
        "my": "Burmese",
        "nb": "Norwegian Bokmål",
        "ne": "Nepali",
        "nl": "Dutch",
        "nso": "Northern Sotho",
        "nya": "Nyanja",
        "or": "Odia",
        "otq": "Querétaro Otomi",
        "pa": "Punjabi",
        "pl": "Polish",
        "prs": "Persian (Afghanistan)",
        "ps": "Pashto",
        "pt": "Portuguese",
        "pt-PT": "Portuguese (Portugal)",
        "ro": "Romanian",
        "ru": "Russian",
        "run": "Rundi",
        "rw": "Kinyarwanda",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr-Cyrl": "Serbian (Cyrillic)",
        "sr-Latn": "Serbian (Latin)",
        "st": "Southern Sotho",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tlh-Latn": "Klingon (Latin)",
        "tn": "Tswana",
        "to": "Tongan",
        "tr": "Turkish",
        "tt": "Tatar",
        "ty": "Tahitian",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "xh": "Xhosa",
        "yo": "Yoruba",
        "yua": "Yucateco",
        "yue": "Cantonese",
        "zh-Hans": "Chinese (Simplified)",
        "zh-Hant": "Chinese (Traditional)",
        "zu": "Zulu",
    },
    "caiyun": {
        "auto": "auto",
        "zh": "Chinese",
        "en": "English",
        "ja": "Japanese",
        "ko": "Korean",
        "es": "Spanish",
        "fr": "French",
        "ru": "Russian",
    },
    "cloudYi": {
        "auto": "auto",
        "all": "Allar",
        "ar": "Arabic",
        "de": "German",
        "en-us": "English (United States)",
        "es": "Spanish",
        "fa": "Persian",
        "fr": "French",
        "hi": "Hindi",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "kk": "Kazakh",
        "km": "Khmer",
        "ko": "Korean",
        "lo": "Lao",
        "ms": "Malay",
        "my": "Burmese",
        "nl": "Dutch",
        "pl": "Polish",
        "pt": "Portuguese",
        "ru": "Russian",
        "sk": "Slovak",
        "th": "Thai",
        "tl": "Filipino",
        "uk": "Ukrainian",
        "vi": "Vietnamese",
        "yue": "Cantonese",
        "zh-cn": "Chinese (China)",
        "zh-tw": "Chinese (Taiwan)",
    },
    "deepl": {
        "auto": "auto",
        "ro": "Romanian",
        "bg": "Bulgarian",
        "ko": "Korean",
        "pl": "Polish",
        "cs": "Czech",
        "es": "Spanish",
        "tr": "Turkish",
        "sl": "Slovenian",
        "zh": "Chinese",
        "ja": "Japanese",
        "et": "Estonian",
        "pt": "Portuguese",
        "de": "German",
        "lt": "Lithuanian",
        "el": "Greek",
        "en": "English",
        "fr": "French",
        "nl": "Dutch",
        "lv": "Latvian",
        "it": "Italian",
        "sv": "Swedish",
        "sk": "Slovak",
        "uk": "Ukrainian",
        "fi": "Finnish",
        "hu": "Hungarian",
        "nb": "Norwegian Bokmål",
        "ru": "Russian",
        "id": "Indonesian",
        "da": "Danish",
    },
    "elia": {
        "auto": "auto",
        "eu": "Basque",
        "gl": "Galician",
        "ca": "Catalan",
        "fr": "French",
        "en": "English",
        "es": "Spanish",
    },
    "google": {
        "auto": "auto",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "Amharic",
        "ar": "Arabic",
        "as": "Assamese",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bho": "Bhojpuri",
        "bm": "Bambara",
        "bn": "Bangla",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "ckb": "Central Kurdish",
        "co": "Corsican",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "doi": "Dogri",
        "dv": "Divehi",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "en-US": "English (United States)",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gn": "Guarani",
        "gom": "Goan Konkani",
        "gu": "Gujarati",
        "ha": "Hausa",
        "haw": "Hawaiian",
        "hi": "Hindi",
        "hmn": "Hmong",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "ilo": "Iloko",
        "is": "Icelandic",
        "it": "Italian",
        "iw": "Hebrew",
        "ja": "Japanese",
        "jw": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "kri": "Krio",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lus": "Mizo",
        "lv": "Latvian",
        "mai": "Maithili",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mni-Mtei": "Manipuri (Meitei Mayek)",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "nso": "Northern Sotho",
        "ny": "Nyanja",
        "om": "Oromo",
        "or": "Odia",
        "pa": "Punjabi",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "sa": "Sanskrit",
        "sd": "Sindhi",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tl": "Filipino",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "zh-CN": "Chinese (China)",
        "zh-TW": "Chinese (Taiwan)",
        "zu": "Zulu",
    },
    "iciba": {
        "auto": "auto",
        "ace": "Achinese",
        "acu": "Achuar-Shiwiar",
        "af": "Afrikaans",
        "agr": "Aguaruna",
        "ake": "Akawaio",
        "am": "Amharic",
        "amu": "Guerrero Amuzgo",
        "ar": "Arabic",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "be": "Belarusian",
        "bem": "Bemba",
        "ber": "Berber languages",
        "bg": "Bulgarian",
        "bi": "Bislama",
        "bn": "Bangla",
        "br": "Breton",
        "bs": "Bosnian",
        "bsn": "Barasana-Eduria",
        "ca": "Catalan",
        "cak": "Kaqchikel",
        "ceb": "Cebuano",
        "cha": "Chamorro",
        "chq": "Quiotepec Chinantec",
        "chr": "Cherokee",
        "cht": "Cholón",
        "cjp": "Cabécar",
        "cni": "Asháninka",
        "co": "Corsican",
        "cop": "Coptic",
        "crs": "Seselwa Creole French",
        "cs": "Czech",
        "cv": "Chuvash",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dik": "Southwestern Dinka",
        "dje": "Zarma",
        "djk": "Eastern Maroon Creole",
        "dop": "Lukpa",
        "dv": "Divehi",
        "dz": "Dzongkha",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fil": "Filipino",
        "fj": "Fijian",
        "fo": "Faroese",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gbi": "Galela",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gu": "Gujarati",
        "gv": "Manx",
        "ha": "Hausa",
        "haw": "Hawaiian",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jac": "Popti'",
        "jiv": "Shuar",
        "jv": "Javanese",
        "jy": "jy",
        "ka": "Georgian",
        "kab": "Kabyle",
        "kbh": "Camsá",
        "kek": "Kekchí",
        "kg": "Kongo",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mam": "Mam",
        "me": "me",
        "mg": "Malagasy",
        "mhr": "Eastern Mari",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mr": "Marathi",
        "mrj": "Western Mari",
        "ms": "Malay",
        "mt": "Maltese",
        "mww": "Hmong Daw",
        "my": "Burmese",
        "ne": "Nepali",
        "nhg": "Tetelcingo Nahuatl",
        "nl": "Dutch",
        "no": "Norwegian",
        "ny": "Nyanja",
        "ojb": "Northwestern Ojibwa",
        "om": "Oromo",
        "or": "Odia",
        "os": "Ossetic",
        "otq": "Querétaro Otomi",
        "pa": "Punjabi",
        "pap": "Papiamento",
        "pck": "Paite Chin",
        "pl": "Polish",
        "pot": "Potawatomi",
        "ppk": "Uma",
        "ps": "Pashto",
        "pt": "Portuguese",
        "quc": "Kʼicheʼ",
        "quw": "Tena Lowland Quichua",
        "rmn": "Balkan Romani",
        "rn": "Rundi",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "sd": "Sindhi",
        "sg": "Sango",
        "shi": "Tachelhit",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "syc": "Classical Syriac",
        "ta": "Tamil",
        "te": "Telugu",
        "tet": "Tetum",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tig": "Tigre",
        "tk": "Turkmen",
        "tmh": "Tamashek",
        "tn": "Tswana",
        "to": "Tongan",
        "tpi": "Tok Pisin",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tw": "Twi",
        "ty": "Tahitian",
        "udm": "Udmurt",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "usp": "Uspanteco",
        "uy": "uy",
        "uz": "Uzbek",
        "ve": "Venda",
        "vi": "Vietnamese",
        "wal": "Wolaytta",
        "war": "Waray",
        "wol": "Wolof",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "yua": "Yucateco",
        "yue": "Cantonese",
        "zh": "Chinese",
        "zu": "Zulu",
    },
    "iflytek": {
        "auto": "auto",
        "af": "Afrikaans",
        "am": "Amharic",
        "ar": "Arabic",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "be": "Belarusian",
        "bem": "Bemba",
        "bg": "Bulgarian",
        "bi": "Bislama",
        "bn": "Bangla",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "cht": "Cholón",
        "cn": "cn",
        "co": "Corsican",
        "crs": "Seselwa Creole French",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fil": "Filipino",
        "fj": "Fijian",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gu": "Gujarati",
        "ha": "Hausa",
        "haw": "Hawaiian",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jv": "Javanese",
        "jy": "jy",
        "ka": "Georgian",
        "kek": "Kekchí",
        "kg": "Kongo",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "ku": "Kurdish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mg": "Malagasy",
        "mhr": "Eastern Mari",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mr": "Marathi",
        "mrj": "Western Mari",
        "ms": "Malay",
        "mt": "Maltese",
        "mww": "Hmong Daw",
        "my": "Burmese",
        "nb": "Norwegian Bokmål",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "ny": "Nyanja",
        "om": "Oromo",
        "os": "Ossetic",
        "otq": "Querétaro Otomi",
        "pa": "Punjabi",
        "pap": "Papiamento",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "rn": "Rundi",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "sd": "Sindhi",
        "sg": "Sango",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "tig": "Tigre",
        "tk": "Turkmen",
        "tn": "Tswana",
        "to": "Tongan",
        "tpi": "Tok Pisin",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tw": "Twi",
        "ty": "Tahitian",
        "udm": "Udmurt",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "war": "Waray",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "yua": "Yucateco",
        "yue": "Cantonese",
        "zu": "Zulu",
    },
    "iflyrec": {
        "auto": "auto",
        "ar": "Arabic",
        "de": "German",
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "it": "Italian",
        "ja": "Japanese",
        "ko": "Korean",
        "ru": "Russian",
        "vi": "Vietnamese",
        "yue": "Cantonese",
        "zh": "Chinese",
    },
    "itranslate": {
        "auto": "auto",
        "af": "Afrikaans",
        "ar-AE": "Arabic (United Arab Emirates)",
        "ar-EG": "Arabic (Egypt)",
        "ar-SA": "Arabic (Saudi Arabia)",
        "az": "Azerbaijani",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "cs": "Czech",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "en": "English",
        "en-AU": "English (Australia)",
        "en-UK": "English (United Kingdom)",
        "en-US": "English (United States)",
        "eo": "Esperanto",
        "es-ES": "Spanish (Spain)",
        "es-MX": "Spanish (Mexico)",
        "es-US": "Spanish (United States)",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fr-CA": "French (Canada)",
        "fr-FR": "French (France)",
        "ga": "Irish",
        "gl": "Galician",
        "gu": "Gujarati",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hmn": "Hmong",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ig": "Igbo",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jw": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "la": "Latin",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "ny": "Nyanja",
        "pa": "Punjabi",
        "pl": "Polish",
        "pt-BR": "Portuguese (Brazil)",
        "pt-PT": "Portuguese (Portugal)",
        "ro": "Romanian",
        "ru": "Russian",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "tl": "Filipino",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "zh-CN": "Chinese (China)",
        "zh-HK": "Chinese (Hong Kong SAR China)",
        "zh-TW": "Chinese (Taiwan)",
        "zu": "Zulu",
    },
    "judic": {"en": "English", "de": "German", "fr": "French", "nl": "Dutch"},
    "languageWire": {
        "auto": "auto",
        "en": "English",
        "de": "German",
        "da": "Danish",
        "sv": "Swedish",
        "nb": "Norwegian Bokmål",
        "fr": "French",
        "es": "Spanish",
        "nl": "Dutch",
    },
    "lingvanex": {
        "auto": "auto",
        "af_ZA": "Afrikaans (South Africa)",
        "am_ET": "Amharic (Ethiopia)",
        "ar_EG": "Arabic (Egypt)",
        "ar_SA": "Arabic (Saudi Arabia)",
        "as_IN": "Assamese (India)",
        "az_AZ": "Azerbaijani (Azerbaijan)",
        "be_BY": "Belarusian (Belarus)",
        "bg_BG": "Bulgarian (Bulgaria)",
        "bn_BD": "Bangla (Bangladesh)",
        "bs_BA": "Bosnian (Bosnia & Herzegovina)",
        "ca_ES": "Catalan (Spain)",
        "ceb_PH": "Cebuano (Philippines)",
        "co_FR": "Corsican (France)",
        "cs_CZ": "Czech (Czechia)",
        "cy_GB": "Welsh (United Kingdom)",
        "da_DK": "Danish (Denmark)",
        "de_DE": "German (Germany)",
        "el_GR": "Greek (Greece)",
        "en_GB": "English (United Kingdom)",
        "eo_WORLD": "Esperanto",
        "es_ES": "Spanish (Spain)",
        "et_EE": "Estonian (Estonia)",
        "eu_ES": "Basque (Spain)",
        "fa_IR": "Persian (Iran)",
        "fi_FI": "Finnish (Finland)",
        "fr_CA": "French (Canada)",
        "fr_FR": "French (France)",
        "fy_NL": "Western Frisian (Netherlands)",
        "ga_IE": "Irish (Ireland)",
        "gd_GB": "Scottish Gaelic (United Kingdom)",
        "gl_ES": "Galician (Spain)",
        "gu_IN": "Gujarati (India)",
        "ha_NE": "Hausa (Niger)",
        "haw_US": "Hawaiian (United States)",
        "he_IL": "Hebrew (Israel)",
        "hi_IN": "Hindi (India)",
        "hmn_CN": "Hmong (China)",
        "hr_HR": "Croatian (Croatia)",
        "ht_HT": "Haitian Creole (Haiti)",
        "hu_HU": "Hungarian (Hungary)",
        "hy_AM": "Armenian (Armenia)",
        "id_ID": "Indonesian (Indonesia)",
        "ig_NG": "Igbo (Nigeria)",
        "is_IS": "Icelandic (Iceland)",
        "it_IT": "Italian (Italy)",
        "ja_JP": "Japanese (Japan)",
        "jv_ID": "Javanese (Indonesia)",
        "ka_GE": "Georgian (Georgia)",
        "kk_KZ": "Kazakh (Kazakhstan)",
        "km_KH": "Khmer (Cambodia)",
        "kn_IN": "Kannada (India)",
        "ko_KR": "Korean (South Korea)",
        "ku_IR": "Kurdish (Iran)",
        "ky_KG": "Kyrgyz (Kyrgyzstan)",
        "la_VAT": "Latin",
        "lb_LU": "Luxembourgish (Luxembourg)",
        "lo_LA": "Lao (Laos)",
        "lt_LT": "Lithuanian (Lithuania)",
        "lv_LV": "Latvian (Latvia)",
        "mg_MG": "Malagasy (Madagascar)",
        "mi_NZ": "Māori (New Zealand)",
        "mk_MK": "Macedonian (North Macedonia)",
        "ml_IN": "Malayalam (India)",
        "mn_MN": "Mongolian (Mongolia)",
        "mr_IN": "Marathi (India)",
        "ms_MY": "Malay (Malaysia)",
        "mt_MT": "Maltese (Malta)",
        "my_MM": "Burmese (Myanmar (Burma))",
        "ne_NP": "Nepali (Nepal)",
        "nl_NL": "Dutch (Netherlands)",
        "no_NO": "Norwegian (Norway)",
        "ny_MW": "Nyanja (Malawi)",
        "or_OR": "Odia (Unknown Region [OR])",
        "pa_PK": "Punjabi (Pakistan)",
        "pl_PL": "Polish (Poland)",
        "ps_AF": "Pashto (Afghanistan)",
        "pt_PT": "Portuguese (Portugal)",
        "ro_RO": "Romanian (Romania)",
        "ru_RU": "Russian (Russia)",
        "rw_RW": "Kinyarwanda (Rwanda)",
        "sd_PK": "Sindhi (Pakistan)",
        "si_LK": "Sinhala (Sri Lanka)",
        "sk_SK": "Slovak (Slovakia)",
        "sl_SI": "Slovenian (Slovenia)",
        "sm_WS": "Samoan (Samoa)",
        "sn_ZW": "Shona (Zimbabwe)",
        "so_SO": "Somali (Somalia)",
        "sq_AL": "Albanian (Albania)",
        "sr-Cyrl_RS": "Serbian (Cyrillic, Serbia)",
        "st_LS": "Southern Sotho (Lesotho)",
        "su_ID": "Sundanese (Indonesia)",
        "sv_SE": "Swedish (Sweden)",
        "sw_TZ": "Swahili (Tanzania)",
        "ta_IN": "Tamil (India)",
        "te_IN": "Telugu (India)",
        "tg_TJ": "Tajik (Tajikistan)",
        "th_TH": "Thai (Thailand)",
        "tk_TM": "Turkmen (Turkmenistan)",
        "tl_PH": "Filipino (Philippines)",
        "tr_TR": "Turkish (Turkey)",
        "tt_TT": "Tatar (Trinidad & Tobago)",
        "ug_CN": "Uyghur (China)",
        "uk_UA": "Ukrainian (Ukraine)",
        "ur_PK": "Urdu (Pakistan)",
        "uz_UZ": "Uzbek (Uzbekistan)",
        "vi_VN": "Vietnamese (Vietnam)",
        "xh_ZA": "Xhosa (South Africa)",
        "yi_IL": "Yiddish (Israel)",
        "yo_NG": "Yoruba (Nigeria)",
        "zh-Hans_CN": "Chinese (Simplified, China)",
        "zh-Hant_TW": "Chinese (Traditional, Taiwan)",
        "zu_ZA": "Zulu (South Africa)",
    },
    "niutrans": {"none": "none"},
    "mglip": {"zh": "Chinese", "mon": "Mongolian", "xle": "Lemnian"},
    "modernMt": {
        "auto": "auto",
        "ace": "Achinese",
        "ar": "Arabic",
        "as": "Assamese",
        "az": "Azerbaijani",
        "ban": "Balinese",
        "bg": "Bulgarian",
        "bho": "Bhojpuri",
        "bjn": "Banjar",
        "bn": "Bangla",
        "bs": "Bosnian",
        "bug": "Buginese",
        "ca": "Catalan",
        "cs": "Czech",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "en": "English",
        "es-419": "Spanish (Latin America)",
        "es-ES": "Spanish (Spain)",
        "et": "Estonian",
        "fi": "Finnish",
        "fj": "Fijian",
        "fr": "French",
        "ga": "Irish",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "ilo": "Iloko",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "ka": "Georgian",
        "kam": "Kamba",
        "kg": "Kongo",
        "ki": "Kikuyu",
        "ko": "Korean",
        "ln": "Lingala",
        "lt": "Lithuanian",
        "lua": "Luba-Lulua",
        "lus": "Mizo",
        "lv": "Latvian",
        "mag": "Magahi",
        "mai": "Maithili",
        "mi": "Māori",
        "min": "Minangkabau",
        "mk": "Macedonian",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "nb": "Norwegian Bokmål",
        "nl": "Dutch",
        "nn": "Norwegian Nynorsk",
        "nso": "Northern Sotho",
        "ny": "Nyanja",
        "or": "Odia",
        "pa": "Punjabi",
        "pag": "Pangasinan",
        "pl": "Polish",
        "plt": "Plateau Malagasy",
        "pt-BR": "Portuguese (Brazil)",
        "pt-PT": "Portuguese (Portugal)",
        "ro": "Romanian",
        "ru": "Russian",
        "sd": "Sindhi",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sq": "Albanian",
        "sr-Cyrl": "Serbian (Cyrillic)",
        "sr-Latn": "Serbian (Latin)",
        "st": "Southern Sotho",
        "sv": "Swedish",
        "sw": "Swahili",
        "th": "Thai",
        "tl": "Filipino",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "vi": "Vietnamese",
        "xh": "Xhosa",
        "yo": "Yoruba",
        "zh-CN": "Chinese (China)",
        "zh-TW": "Chinese (Taiwan)",
        "zu": "Zulu",
    },
    "myMemory": {
        "auto": "auto",
        "acf-LC": "Saint Lucian Creole French (St. Lucia)",
        "af-ZA": "Afrikaans (South Africa)",
        "aig-AG": "Antigua and Barbuda Creole English (Antigua & Barbuda)",
        "am-ET": "Amharic (Ethiopia)",
        "ar-SA": "Arabic (Saudi Arabia)",
        "az-AZ": "Azerbaijani (Azerbaijan)",
        "bah-BS": "Bahamas Creole English (Bahamas)",
        "be-BY": "Belarusian (Belarus)",
        "bem-ZM": "Bemba (Zambia)",
        "bg-BG": "Bulgarian (Bulgaria)",
        "bi-VU": "Bislama (Vanuatu)",
        "bjs-BB": "Bajan (Barbados)",
        "bn-IN": "Bangla (India)",
        "bo-CN": "Tibetan (China)",
        "br-FR": "Breton (France)",
        "bs-BA": "Bosnian (Bosnia & Herzegovina)",
        "ca-ES": "Catalan (Spain)",
        "cb-PH": "cb-PH",
        "ch-GU": "Chamorro (Guam)",
        "ckb-IQ": "Central Kurdish (Iraq)",
        "cop-EG": "Coptic (Egypt)",
        "crs-SC": "Seselwa Creole French (Seychelles)",
        "cs-CZ": "Czech (Czechia)",
        "cy-GB": "Welsh (United Kingdom)",
        "da-DK": "Danish (Denmark)",
        "de-CH": "German (Switzerland)",
        "de-DE": "German (Germany)",
        "dv-MV": "Divehi (Maldives)",
        "dz-BT": "Dzongkha (Bhutan)",
        "el-GR": "Greek (Greece)",
        "en-GB": "English (United Kingdom)",
        "eo-EU": "Esperanto (European Union)",
        "es-ES": "Spanish (Spain)",
        "et-EE": "Estonian (Estonia)",
        "eu-ES": "Basque (Spain)",
        "fa-IR": "Persian (Iran)",
        "fi-FI": "Finnish (Finland)",
        "fn-FNG": "fn-FNG",
        "fo-FO": "Faroese (Faroe Islands)",
        "fr-FR": "French (France)",
        "ga-IE": "Irish (Ireland)",
        "gcl-GD": "Grenadian Creole English (Grenada)",
        "gd-GB": "Scottish Gaelic (United Kingdom)",
        "gl-ES": "Galician (Spain)",
        "grc-GR": "Ancient Greek (Greece)",
        "gu-IN": "Gujarati (India)",
        "gv-IM": "Manx (Isle of Man)",
        "gyn-GY": "Guyanese Creole English (Guyana)",
        "ha-NE": "Hausa (Niger)",
        "haw-US": "Hawaiian (United States)",
        "he-IL": "Hebrew (Israel)",
        "hi-IN": "Hindi (India)",
        "hr-HR": "Croatian (Croatia)",
        "ht-HT": "Haitian Creole (Haiti)",
        "hu-HU": "Hungarian (Hungary)",
        "hy-AM": "Armenian (Armenia)",
        "id-ID": "Indonesian (Indonesia)",
        "is-IS": "Icelandic (Iceland)",
        "it-IT": "Italian (Italy)",
        "ja-JP": "Japanese (Japan)",
        "jam-JM": "Jamaican Creole English (Jamaica)",
        "jv-ID": "Javanese (Indonesia)",
        "ka-GE": "Georgian (Georgia)",
        "kab-DZ": "Kabyle (Algeria)",
        "kea-CV": "Kabuverdianu (Cape Verde)",
        "kk-KZ": "Kazakh (Kazakhstan)",
        "kl-GL": "Kalaallisut (Greenland)",
        "km-KM": "Khmer (Comoros)",
        "kn-IN": "Kannada (India)",
        "ko-KR": "Korean (South Korea)",
        "ku-TR": "Kurdish (Turkey)",
        "ky-KG": "Kyrgyz (Kyrgyzstan)",
        "la-VA": "Latin (Vatican City)",
        "lb-LU": "Luxembourgish (Luxembourg)",
        "lo-LA": "Lao (Laos)",
        "lt-LT": "Lithuanian (Lithuania)",
        "lv-LV": "Latvian (Latvia)",
        "men-SL": "Mende (Sierra Leone)",
        "mfe-MU": "Morisyen (Mauritius)",
        "mg-MG": "Malagasy (Madagascar)",
        "mh-MH": "Marshallese (Marshall Islands)",
        "mi-NZ": "Māori (New Zealand)",
        "mk-MK": "Macedonian (North Macedonia)",
        "mn-MN": "Mongolian (Mongolia)",
        "ms-MY": "Malay (Malaysia)",
        "mt-MT": "Maltese (Malta)",
        "my-MM": "Burmese (Myanmar (Burma))",
        "ne-NP": "Nepali (Nepal)",
        "niu-NU": "Niuean (Niue)",
        "nl-NL": "Dutch (Netherlands)",
        "no-NO": "Norwegian (Norway)",
        "ny-MW": "Nyanja (Malawi)",
        "pa-IN": "Punjabi (India)",
        "pap-CW": "Papiamento (Curaçao)",
        "pau-PW": "Palauan (Palau)",
        "pis-SB": "Pijin (Solomon Islands)",
        "pl-PL": "Polish (Poland)",
        "pot-US": "Potawatomi (United States)",
        "pov-GW": "Upper Guinea Crioulo (Guinea-Bissau)",
        "ppk-ID": "Uma (Indonesia)",
        "ps-PK": "Pashto (Pakistan)",
        "pt-PT": "Portuguese (Portugal)",
        "qu-PE": "Quechua (Peru)",
        "rm-RO": "Romansh (Romania)",
        "rn-BI": "Rundi (Burundi)",
        "ro-RO": "Romanian (Romania)",
        "ru-RU": "Russian (Russia)",
        "rw-RW": "Kinyarwanda (Rwanda)",
        "sg-CF": "Sango (Central African Republic)",
        "si-LK": "Sinhala (Sri Lanka)",
        "sk-SK": "Slovak (Slovakia)",
        "sl-SI": "Slovenian (Slovenia)",
        "sm-WS": "Samoan (Samoa)",
        "sn-ZW": "Shona (Zimbabwe)",
        "so-SO": "Somali (Somalia)",
        "sq-AL": "Albanian (Albania)",
        "sr-RS": "Serbian (Serbia)",
        "srn-SR": "Sranan Tongo (Suriname)",
        "st-ST": "Southern Sotho (São Tomé & Príncipe)",
        "sv-SE": "Swedish (Sweden)",
        "svc-VC": "Vincentian Creole English (St. Vincent & Grenadines)",
        "sw-SZ": "Swahili (Eswatini)",
        "syc-TR": "Classical Syriac (Turkey)",
        "ta-LK": "Tamil (Sri Lanka)",
        "te-IN": "Telugu (India)",
        "tet-TL": "Tetum (Timor-Leste)",
        "tg-TJ": "Tajik (Tajikistan)",
        "th-TH": "Thai (Thailand)",
        "ti-TI": "Tigrinya (Unknown Region [TI])",
        "tk-TM": "Turkmen (Turkmenistan)",
        "tkl-TK": "Tokelau (Tokelau)",
        "tl-PH": "Filipino (Philippines)",
        "tmh-DZ": "Tamashek (Algeria)",
        "tn-BW": "Tswana (Botswana)",
        "to-TO": "Tongan (Tonga)",
        "tpi-PG": "Tok Pisin (Papua New Guinea)",
        "tr-TR": "Turkish (Turkey)",
        "tvl-TV": "Tuvalu (Tuvalu)",
        "uk-UA": "Ukrainian (Ukraine)",
        "ur-PK": "Urdu (Pakistan)",
        "uz-UZ": "Uzbek (Uzbekistan)",
        "vi-VN": "Vietnamese (Vietnam)",
        "vic-US": "Virgin Islands Creole English (United States)",
        "wls-WF": "Wallisian (Wallis & Futuna)",
        "wo-SN": "Wolof (Senegal)",
        "xh-ZA": "Xhosa (South Africa)",
        "yi-YD": "Yiddish (Yemen)",
        "zdj-KM": "Ngazidja Comorian (Comoros)",
        "zh-CN": "Chinese (China)",
        "zh-TW": "Chinese (Taiwan)",
        "zu-ZA": "Zulu (South Africa)",
    },
    "papago": {
        "auto": "auto",
        "de": "German",
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "hi": "Hindi",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "ko": "Korean",
        "pt": "Portuguese",
        "ru": "Russian",
        "th": "Thai",
        "vi": "Vietnamese",
        "zh-CN": "Chinese (China)",
        "zh-TW": "Chinese (Taiwan)",
    },
    "qqFanyi": {
        "auto": "auto",
        "en": "English",
        "zh": "Chinese",
        "fr": "French",
        "es": "Spanish",
        "it": "Italian",
        "de": "German",
        "tr": "Turkish",
        "ru": "Russian",
        "pt": "Portuguese",
        "vi": "Vietnamese",
        "id": "Indonesian",
        "ms": "Malay",
        "th": "Thai",
        "jp": "jp",
        "kr": "Kanuri",
        "ar": "Arabic",
        "hi": "Hindi",
    },
    "qqTranSmart": {
        "auto": "auto",
        "ach": "Acoli",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "Amharic",
        "an": "Aragonese",
        "ar": "Arabic",
        "arn": "Mapuche",
        "ast": "Asturian",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "bo": "Tibetan",
        "br": "Breton",
        "bs": "Bosnian",
        "ca": "Catalan",
        "cgg": "Chiga",
        "cnr": "Serbian (Montenegro)",
        "cs": "Czech",
        "csb": "Kashubian",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dev": "Domung",
        "dz": "Dzongkha",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fil": "Filipino",
        "fo": "Faroese",
        "fr": "French",
        "fur": "Friulian",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gu": "Gujarati",
        "gun": "Mbyá Guaraní",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "ia": "Interlingua",
        "id": "Indonesian",
        "is": "Icelandic",
        "it": "Italian",
        "iw": "Hebrew",
        "ja": "Japanese",
        "jbo": "Lojban",
        "jv": "Javanese",
        "ka": "Georgian",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "ku": "Kurdish",
        "kw": "Cornish",
        "ky": "Kyrgyz",
        "lb": "Luxembourgish",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mai": "Maithili",
        "mfe": "Morisyen",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mnk": "Mandinka",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "nah": "Nahuatl languages",
        "nap": "Neapolitan",
        "nb": "Norwegian Bokmål",
        "ne": "Nepali",
        "nl": "Dutch",
        "nn": "Norwegian Nynorsk",
        "no": "Norwegian",
        "nso": "Northern Sotho",
        "oc": "Occitan",
        "or": "Odia",
        "pa": "Punjabi",
        "pap": "Papiamento",
        "pl": "Polish",
        "pms": "Piedmontese",
        "ps": "Pashto",
        "pt": "Portuguese",
        "pt-BR": "Portuguese (Brazil)",
        "pt-PT": "Portuguese (Portugal)",
        "rm": "Romansh",
        "ro": "Romanian",
        "ru": "Russian",
        "sah": "Sakha",
        "sco": "Scots",
        "se": "Northern Sami",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "son": "Songhai languages",
        "sq": "Albanian",
        "sr": "Serbian",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tl": "Filipino",
        "tr": "Turkish",
        "tt": "Tatar",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "vi": "Vietnamese",
        "wa": "Walloon",
        "wo": "Wolof",
        "yo": "Yoruba",
        "zh": "Chinese",
    },
    "reverso": {
        "auto": "auto",
        "af": "Afrikaans",
        "ar": "Arabic",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "cs": "Czech",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "en": "English",
        "es": "Spanish",
        "et": "Estonian",
        "fa": "Persian",
        "fi": "Finnish",
        "fr": "French",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hu": "Hungarian",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "ko": "Korean",
        "lt": "Lithuanian",
        "nl": "Dutch",
        "no": "Norwegian",
        "pe": "pe",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "ptb": "ptb",
        "ro": "Romanian",
        "ru": "Russian",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "sr": "Serbian",
        "sv": "Swedish",
        "th": "Thai",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "vi": "Vietnamese",
        "zh": "Chinese",
    },
    "sogou": {
        "auto": "auto",
        "ar": "Arabic",
        "pl": "Polish",
        "da": "Danish",
        "de": "German",
        "ru": "Russian",
        "fr": "French",
        "fi": "Finnish",
        "ko": "Korean",
        "nl": "Dutch",
        "cs": "Czech",
        "pt": "Portuguese",
        "ja": "Japanese",
        "sv": "Swedish",
        "th": "Thai",
        "tr": "Turkish",
        "es": "Spanish",
        "hu": "Hungarian",
        "en": "English",
        "it": "Italian",
        "vi": "Vietnamese",
        "zh-CHS": "Chinese",
    },
    "sysTran": {
        "auto": "auto",
        "ar": "Arabic",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "ca": "Catalan",
        "cs": "Czech",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "en": "English",
        "es": "Spanish",
        "et": "Estonian",
        "fa": "Persian",
        "fi": "Finnish",
        "fr": "French",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "it": "Italian",
        "ja": "Japanese",
        "ka": "Georgian",
        "ko": "Korean",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "ms": "Malay",
        "my": "Burmese",
        "nl": "Dutch",
        "no": "Norwegian",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "ro": "Romanian",
        "ru": "Russian",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "th": "Thai",
        "tl": "Filipino",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "vi": "Vietnamese",
        "zh-Hans": "Chinese (Simplified)",
        "zh-Hant": "Chinese (Traditional)",
    },
    "tilde": {"none": "none"},
    "translateCom": {
        "auto": "auto",
        "en": "English",
        "fr": "French",
        "de": "German",
        "it": "Italian",
        "pt": "Portuguese",
        "pt-br": "Portuguese (Brazil)",
        "ru": "Russian",
        "es": "Spanish",
        "fr-ca": "French (Canada)",
        "ja": "Japanese",
        "zh": "Chinese",
        "zh-TW": "Chinese (Taiwan)",
        "ko": "Korean",
        "es-la": "Spanish (Laos)",
        "pl": "Polish",
        "nl": "Dutch",
        "ro": "Romanian",
        "fa": "Persian",
        "ar": "Arabic",
        "uk": "Ukrainian",
        "en-gb": "English (United Kingdom)",
    },
    "translateMe": {
        "auto": "auto",
        "Arabic": "Arabic",
        "Bengali": "Bengali",
        "Chinese": "Chinese",
        "English": "English",
        "French": "French",
        "German": "German",
        "Hindi": "Hindi",
        "Indonesian": "Indonesian",
        "Italian": "Italian",
        "Japanese": "Japanese",
        "Portuguese": "Portuguese",
        "Russian": "Russian",
        "Spanish": "Spanish",
        "Tamil": "Tamil",
        "Turkish": "Turkish",
        "Zulu": "Zulu",
    },
    "utibet": {"ti": "Tigrinya", "zh": "Chinese"},
    "volcEngine": {
	    "detect": "detect",
        "aa": "Afar",
        "ab": "Abkhazian",
        "ae": "Avestan",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "Amharic",
        "an": "Aragonese",
        "ar": "Arabic",
        "as": "Assamese",
        "av": "Avaric",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bh": "Bihari languages",
        "bi": "Bislama",
        "bm": "Bambara",
        "bn": "Bangla",
        "bo": "Tibetan",
        "br": "Breton",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ce": "Chechen",
        "ch": "Chamorro",
        "co": "Corsican",
        "cr": "Cree",
        "cs": "Czech",
        "cu": "Church Slavic",
        "cv": "Chuvash",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "dv": "Divehi",
        "dz": "Dzongkha",
        "ee": "Ewe",
        "el": "Greek",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "ff": "Fulah",
        "fi": "Finnish",
        "fj": "Fijian",
        "fo": "Faroese",
        "fr": "French",
        "fy": "Western Frisian",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gn": "Guarani",
        "gu": "Gujarati",
        "gv": "Manx",
        "ha": "Hausa",
        "he": "Hebrew",
        "hi": "Hindi",
        "hi-latn": "Hindi (Latin)",
        "ho": "Hiri Motu",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "hz": "Herero",
        "ia": "Interlingua",
        "id": "Indonesian",
        "ie": "Interlingue",
        "ig": "Igbo",
        "ii": "Sichuan Yi",
        "ik": "Inupiaq",
        "io": "Ido",
        "is": "Icelandic",
        "it": "Italian",
        "iu": "Inuktitut",
        "ja": "Japanese",
        "jv": "Javanese",
        "ka": "Georgian",
        "kg": "Kongo",
        "ki": "Kikuyu",
        "kj": "Kuanyama",
        "kk": "Kazakh",
        "kl": "Kalaallisut",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "kr": "Kanuri",
        "ks": "Kashmiri",
        "ku": "Kurdish",
        "kv": "Komi",
        "kw": "Cornish",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lg": "Ganda",
        "li": "Limburgish",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lu": "Luba-Katanga",
        "lv": "Latvian",
        "mg": "Malagasy",
        "mh": "Marshallese",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mo": "Romanian",
        "mr": "Marathi",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "na": "Nauru",
        "nb": "Norwegian Bokmål",
        "nd": "North Ndebele",
        "ne": "Nepali",
        "ng": "Ndonga",
        "nl": "Dutch",
        "nn": "Norwegian Nynorsk",
        "no": "Norwegian",
        "nr": "South Ndebele",
        "nv": "Navajo",
        "ny": "Nyanja",
        "oc": "Occitan",
        "oj": "Ojibwa",
        "om": "Oromo",
        "or": "Odia",
        "os": "Ossetic",
        "pa": "Punjabi",
        "pi": "Pali",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "rm": "Romansh",
        "rn": "Rundi",
        "ro": "Romanian",
        "ru": "Russian",
        "rw": "Kinyarwanda",
        "sa": "Sanskrit",
        "sc": "Sardinian",
        "sd": "Sindhi",
        "se": "Northern Sami",
        "sg": "Sango",
        "sh": "Serbian (Latin)",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sm": "Samoan",
        "sn": "Shona",
        "so": "Somali",
        "sq": "Albanian",
        "sr": "Serbian",
        "ss": "Swati",
        "st": "Southern Sotho",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "tk": "Turkmen",
        "tl": "Filipino",
        "tn": "Tswana",
        "to": "Tongan",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tw": "Twi",
        "ty": "Tahitian",
        "ug": "Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "ve": "Venda",
        "vi": "Vietnamese",
        "vo": "Volapük",
        "wa": "Walloon",
        "wo": "Wolof",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "za": "Zhuang",
        "zh": "Chinese",
        "zh-Hant": "Chinese (Traditional)",
        "zu": "Zulu",
    },
    "yandex": {
        "auto": "auto",
        "af": "Afrikaans",
        "am": "Amharic",
        "ar": "Arabic",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "be": "Belarusian",
        "bg": "Bulgarian",
        "bn": "Bangla",
        "bs": "Bosnian",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "cs": "Czech",
        "cv": "Chuvash",
        "cy": "Welsh",
        "da": "Danish",
        "de": "German",
        "el": "Greek",
        "emj": "emj",
        "en": "English",
        "eo": "Esperanto",
        "es": "Spanish",
        "et": "Estonian",
        "eu": "Basque",
        "fa": "Persian",
        "fi": "Finnish",
        "fr": "French",
        "ga": "Irish",
        "gd": "Scottish Gaelic",
        "gl": "Galician",
        "gu": "Gujarati",
        "he": "Hebrew",
        "hi": "Hindi",
        "hr": "Croatian",
        "ht": "Haitian Creole",
        "hu": "Hungarian",
        "hy": "Armenian",
        "id": "Indonesian",
        "is": "Icelandic",
        "it": "Italian",
        "ja": "Japanese",
        "jv": "Javanese",
        "ka": "Georgian",
        "kazlat": "kazlat",
        "kk": "Kazakh",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Korean",
        "ky": "Kyrgyz",
        "la": "Latin",
        "lb": "Luxembourgish",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lv": "Latvian",
        "mg": "Malagasy",
        "mhr": "Eastern Mari",
        "mi": "Māori",
        "mk": "Macedonian",
        "ml": "Malayalam",
        "mn": "Mongolian",
        "mr": "Marathi",
        "mrj": "Western Mari",
        "ms": "Malay",
        "mt": "Maltese",
        "my": "Burmese",
        "ne": "Nepali",
        "nl": "Dutch",
        "no": "Norwegian",
        "pa": "Punjabi",
        "pap": "Papiamento",
        "pl": "Polish",
        "pt": "Portuguese",
        "pt-BR": "Portuguese (Brazil)",
        "ro": "Romanian",
        "ru": "Russian",
        "sah": "Sakha",
        "si": "Sinhala",
        "sjn": "Sindarin",
        "sk": "Slovak",
        "sl": "Slovenian",
        "sq": "Albanian",
        "sr": "Serbian",
        "sr-Latn": "Serbian (Latin)",
        "su": "Sundanese",
        "sv": "Swedish",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "tl": "Filipino",
        "tr": "Turkish",
        "tt": "Tatar",
        "udm": "Udmurt",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "uzbcyr": "uzbcyr",
        "vi": "Vietnamese",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "zh": "Chinese",
        "zu": "Zulu",
    },
    "yeekit": {
        "auto": "auto",
        "zh": "Chinese",
        "en": "English",
        "ar": "Arabic",
        "de": "German",
        "ru": "Russian",
        "fr": "French",
        "cz": "cz",
        "pt": "Portuguese",
        "jp": "jp",
        "es": "Spanish",
    },
    "youdao": {
        "auto": "auto",
        "ar": "Arabic",
        "de": "German",
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "id": "Indonesian",
        "ja": "Japanese",
        "ko": "Korean",
        "pt": "Portuguese",
        "ru": "Russian",
        "vi": "Vietnamese",
        "zh-CHS": "Chinese",
    },
}

# Argos very long
# "argos": ['auto', 'ar', 'az', 'ca', 'cs', 'da', 'de', 'el', 'en', 'eo', 'es', 'fa', 'fi', 'fr', 'ga', 'he', 'hi', 'hu', 'id', 'it', 'iw', 'ja', 'ko', 'nl', 'pl', 'pt', 'ru', 'sk', 'sv', 'tr', 'uk', 'zh'],

# Stopped working
# "niutrans": ['ace', 'ach', 'acr', 'acu', 'ada', 'adh', 'af', 'agr', 'ake', 'am', 'amk', 'amu', 'any', 'ar', 'arn', 'ata', 'ay', 'az', 'azb', 'ba', 'bam', 'bas', 'bba', 'bch', 'bci', 'bcl', 'bdh', 'bdu', 'be', 'bem', 'ber', 'bfa', 'bg', 'bhw', 'bi', 'bin', 'bn', 'bno', 'bnp', 'bqj', 'bqp', 'br', 'bs', 'bsn', 'btx', 'bum', 'bus', 'byr', 'bzj', 'ca', 'cab', 'cak', 'cas', 'cbl', 'cce', 'ccp', 'cdf', 'ceb', 'cfm', 'cha', 'che', 'chk', 'chq', 'chr', 'cht', 'cjk', 'cjp', 'ckb', 'cki', 'cnh', 'cni', 'co', 'cop', 'cpb', 'crh', 'crs', 'cs', 'ctd', 'cv', 'cy', 'czt', 'da', 'de', 'dhv', 'dik', 'djk', 'dop', 'dtp', 'dua', 'duo', 'dv', 'dyu', 'dz', 'ee', 'efi', 'el', 'en', 'enx', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'tl', 'fj', 'fo', 'fr', 'fuv', 'fy', 'ga', 'gaa', 'gbi', 'gbo', 'gd', 'gil', 'gl', 'gnw', 'gof', 'gu', 'gub', 'guc', 'gug', 'gur', 'guw', 'gv', 'gym', 'ha', 'haw', 'he', 'her', 'hi', 'hil', 'hlb', 'hmo', 'hr', 'ht', 'hu', 'hui', 'huv', 'hwc', 'hy', 'iba', 'ibg', 'id', 'ifa', 'ifb', 'ify', 'ig', 'ikk', 'ilo', 'iou', 'is', 'ish', 'iso', 'it', 'izz', 'ja', 'jac', 'jae', 'jiv', 'jmc', 'jv', 'ka', 'ka', 'kab', 'kac', 'kam', 'kbh', 'kbo', 'kbp', 'kea', 'kek', 'keo', 'kg', 'kik', 'kk', 'kle', 'km', 'kmb', 'kn', 'knj', 'ko', 'kpg', 'kqn', 'krs', 'ksd', 'ku', 'kwy', 'ky', 'kyu', 'la', 'lb', 'lcm', 'lcp', 'lg', 'ln', 'lnd', 'lo', 'loz', 'lsi', 'lt', 'lua', 'lub', 'lue', 'lun', 'lus', 'lv', 'mad', 'mh', 'mam', 'map', 'mau', 'mbb', 'mdy', 'cnr', 'meu', 'mfe', 'mg', 'mhr', 'mi', 'mk', 'ml', 'mn', 'mni', 'mn', 'mos', 'mps', 'mr', 'mrj', 'mrw', 'ms', 'mt', 'muv', 'hmn', 'my', 'nav', 'nba', 'ndc', 'ndo', 'ne', 'ngl', 'nhg', 'nia', 'nij', 'niu', 'nl', 'no', 'nop', 'ntm', 'ny', 'nyk', 'nyn', 'nyu', 'nyy', 'nzi', 'ojb', 'om', 'ond', 'or', 'os', 'otq', 'pa', 'pag', 'pap', 'pck', 'pcm', 'pil', 'pis', 'pl', 'poh', 'pon', 'pot', 'ppk', 'prk', 'ps', 'pss', 'pt', 'ptu', 'quc', 'quh', 'quw', 'quz', 'qxr', 'rar', 'rmn', 'rn', 'rnd', 'ro', 'ru', 'rug', 'rw', 'sd', 'seh', 'sg', 'shi', 'shp', 'si', 'sid', 'sk', 'sl', 'sm', 'sn', 'so', 'sop', 'spy', 'sq', 'sr', 'srm', 'ssd', 'ssx', 'st', 'su', 'sv', 'sw', 'swc', 'swp', 'sxn', 'syc', 'ta', 'tbz', 'tdt', 'te', 'teo', 'tet', 'tex', 'tg', 'tl', 'th', 'ti', 'tig', 'tih', 'tiv', 'tk', 'tll', 'tmh', 'tn', 'to', 'toj', 'tpi', 'tpm', 'tr', 'ts', 'tsc', 'tt', 'ttj', 'tum', 'tvl', 'tw', 'ty', 'tyv', 'tzh', 'tzo', 'udm', 'uk', 'umb', 'ur', 'urh', 'usp', 'uz', 've', 'vi', 'vun', 'wal', 'war', 'wes', 'wls', 'wlx', 'wo', 'wrs', 'wsk', 'xal', 'xh', 'xsm', 'yap', 'yi', 'yo', 'yon', 'yua', 'yue', 'zh', 'zne', 'zu', 'zyb'],
# "yandex": [],
# "utibet": [],
# "iflytek": ['af', 'am', 'ar', 'az', 'ba', 'be', 'bem', 'bg', 'bi', 'bn', 'bs', 'ca', 'ceb', 'cht', 'cn', 'co', 'crs', 'cs', 'cy', 'da', 'de', 'ee', 'el', 'en', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fil', 'fj', 'fr', 'fy', 'ga', 'gd', 'gl', 'gu', 'ha', 'haw', 'he', 'hi', 'hr', 'ht', 'hu', 'hy', 'id', 'ig', 'is', 'it', 'ja', 'jv', 'jy', 'ka', 'kek', 'kg', 'kk', 'km', 'kn', 'ko', 'ku', 'ky', 'la', 'lb', 'lg', 'ln', 'lo', 'lt', 'lv', 'mg', 'mhr', 'mi', 'mk', 'ml', 'mr', 'mrj', 'ms', 'mt', 'mww', 'my', 'nb', 'ne', 'nl', 'no', 'ny', 'om', 'os', 'otq', 'pa', 'pap', 'pl', 'ps', 'pt', 'rn', 'ro', 'ru', 'rw', 'sd', 'sg', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'tig', 'tk', 'tn', 'to', 'tpi', 'tr', 'ts', 'tt', 'tw', 'ty', 'udm', 'uk', 'ur', 'uz', 'vi', 'war', 'xh', 'yi', 'yo', 'yua', 'yue', 'zu'],
# "iflyrec": ['auto', 'ar', 'de', 'en', 'es', 'fr', 'it', 'ja', 'ko', 'ru', 'vi', 'yue', 'zh'],

